### ISSUE TITLE
Unclear error thrown on Python import error

### ISSUE THREAD

**Issue by misharigot** [onnovalkering/brane#5]
**Describe the bug**
When an import error in Python occurs, the following error is thrown by Brane:

> Decoding failed, encoded input doesn't seem to be Base64 encoded.

I highly suspect that this error also occurs for other arbitrary Python errors. Also possibly related to https://github.com/onnovalkering/brane/issues/4.

On the following python code:

```python

def downcast(input_path, output_path):
  import doesnotexist

  return f"{input_path} {output_path}"

if __name__ == "__main__":
  command = sys.argv[1]
  argument = os.environ["INPUT"]
  argument2 = os.environ["TEMP"]
  functions = {
    "downcast": downcast,
  }
  output = functions[command](argument, argument2)
  print(yaml.dump({"output": output}))
```

container.yml

```yml
name: foobar
version: 0.1.12
kind: compute

dependencies:
  - python3
  - python3-pip
  - python3-yaml

# install:
  # - pip3 install pandas fastparquet numpy

files:
  - run.py

entrypoint:
  kind: task
  exec: run.py

actions:
  'downcast':
    command:
      args:
        - downcast
    input:
      - type: string
        name: input
      - type: string
        name: temp
    output:
      - type: string
        name: output

```

**To reproduce**
1. Create a Python function.
2. Branify the Python function by writing a `container.yml` for it and test that it works.
3. Introduce an import that will fail, such as `import doesnotexist`.
4. Run the function through Brane.

**Expected behavior**
A more descriptive Brane error should be thrown, **in addition** to the Python error itself.

**Additional context**
The console output:

<img src="https://user-images.githubusercontent.com/15928604/119569574-34eff680-bdaf-11eb-8454-60f7e610140a.png" height=200>

**Comment by misharigot** [comment]
I am trying to import a local module now (utils.py), but I cannot seem to get it working. 

I have include the file in the files key in `container.yml`, but I get the same error as the one I reported in the issue description above.

```yml
name: foobar
version: 0.1.15
kind: compute

dependencies:
  - python3
  - python3-pip
  - python3-yaml

# install:
  # - pip3 install pandas fastparquet numpy

files:
  - run.py
  - utils.py

entrypoint:
  kind: task
  exec: run.py

actions:
  'downcast':
    command:
      args:
        - downcast
    input:
      - type: string
        name: input
      - type: string
        name: temp
    output:
      - type: string
        name: output
```

`utils.py`:

```python
def return_foo():
    return "foo"
```

`run.py` (imports `utils.py` and runs a function from it):

```python
#!/usr/bin/env python3

import os
import sys
import yaml

from utils import return_foo


def downcast(input_path, output_path):
  return f"{return_foo()} downcast successful! {input_path} {output_path}"


if __name__ == "__main__":
  command = sys.argv[1]
  argument = os.environ["INPUT"]
  argument2 = os.environ["TEMP"]
  functions = {
    "downcast": downcast,
  }
  output = functions[command](argument, argument2)
  print(yaml.dump({"output": output}))
```
